[package]
name = "d8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
flamegraph = "0.6.4"
indicatif = "0.17.7"
num = "0.4.1"
prehash = "1.0.0"
winnow = "0.5.26"
